name: Setup Environment
description: Sources .envrc and exports SHELLSHOCK_ENVRC for scripts

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        PROJ="$(git rev-parse --show-toplevel)"
        echo "SHELLSHOCK_ENVRC=source $PROJ/.envrc" >> "$GITHUB_ENV"
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
